import React, { useEffect, useMemo, useState } from 'react';
import { useEnterprise } from '../../context/EnterpriseContext';
import '../../pages/Enterprise/EnterpriseTaxCompliance.css';
import '../../pages/Enterprise/EnterpriseActionPages.css';

const TaxMonitoring = () => {
  const { entities, fetchEntityComplianceDeadlines } = useEnterprise();

  const [selectedEntityId, setSelectedEntityId] = useState('');
  const selectedEntity = useMemo(() => {
    if (!selectedEntityId) return null;
    return entities.find((e) => String(e.id) === String(selectedEntityId)) || null;
  }, [entities, selectedEntityId]);

  const [complianceDeadlines, setComplianceDeadlines] = useState([]);
  const [alertFilter, setAlertFilter] = useState('all');
  const [dataError, setDataError] = useState(null);

  useEffect(() => {
    if (selectedEntityId) return;
    if (!entities || entities.length === 0) return;
    setSelectedEntityId(String(entities[0].id));
  }, [entities, selectedEntityId]);

  useEffect(() => {
    if (!selectedEntityId) return;
    fetchEntityComplianceDeadlines(selectedEntityId)
      .then((deadlines) => setComplianceDeadlines(deadlines || []))
      .catch((err) => setDataError(err?.message || 'Failed to load monitoring data'));
  }, [selectedEntityId, fetchEntityComplianceDeadlines]);

  const complianceAlerts = useMemo(() => {
    const now = new Date();
    return (complianceDeadlines || []).map((d) => {
      const deadlineDate = d.deadline_date ? new Date(d.deadline_date) : null;
      const daysLeft = deadlineDate
        ? Math.ceil((deadlineDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24))
        : null;
      let severity = 'low';
      if (d.status === 'overdue') severity = 'high';
      else if (daysLeft !== null && daysLeft <= 7) severity = 'high';
      else if (daysLeft !== null && daysLeft <= 30) severity = 'medium';
      return {
        id: d.id,
        message: d.title,
        severity,
        date: d.deadline_date,
        autoGenerated: false,
        actions: ['view', 'set-reminder'],
      };
    });
  }, [complianceDeadlines]);

  const filtered = alertFilter === 'all'
    ? complianceAlerts
    : complianceAlerts.filter((a) => a.severity === alertFilter);

  return (
    <div className="enterprise-action-page">
      <section className="action-page-hero">
        <div className="action-page-copy">
          <span className="action-page-kicker">Compliance — Monitoring</span>
          <h1 className="action-page-title">Real-Time Compliance Monitoring</h1>
          <p className="action-page-subtitle">Automated detection of compliance risks and deadlines.</p>
          <div className="action-page-actions">
            <select
              className="entity-selector"
              value={selectedEntityId}
              onChange={(e) => setSelectedEntityId(e.target.value)}
              disabled={!entities || entities.length === 0}
            >
              {(!entities || entities.length === 0) ? (
                <option value="">No entities</option>
              ) : (
                entities.map((ent) => (
                  <option key={ent.id} value={String(ent.id)}>
                    {ent.name} ({ent.country})
                  </option>
                ))
              )}
            </select>
            {dataError && <span className="status-badge warning">{dataError}</span>}
          </div>
        </div>
        <div className="action-page-badge">{selectedEntity?.country || 'Global'}</div>
      </section>

      <div className="monitoring-section">
        <div className="section-header">
          <div className="header-actions">
            <div className="monitoring-status">
              <span>Monitoring Active</span>
            </div>
          </div>
        </div>

        <div className="monitoring-dashboard">
          <div className="status-overview">
            <div className="status-card">
              <div className="status-info">
                <h3>System Health</h3>
                <p>All monitoring systems operational</p>
                <span className="status-badge operational">Operational</span>
              </div>
            </div>
            <div className="status-card">
              <div className="status-info">
                <h3>Last Scan</h3>
                <p>Completed 2 minutes ago</p>
                <span className="status-badge recent">Recent</span>
              </div>
            </div>
            <div className="status-card">
              <div className="status-info">
                <h3>Active Alerts</h3>
                <p>
                  {complianceAlerts.filter((a) => a.severity === 'high').length} critical,{' '}
                  {complianceAlerts.filter((a) => a.severity === 'medium').length} medium
                </p>
                <span className="status-badge alerts">Monitoring</span>
              </div>
            </div>
          </div>
        </div>

        <div className="alerts-panel">
          <div className="alerts-header">
            <h3>Active Alerts ({complianceAlerts.length})</h3>
            <div className="alert-filters">
              <button className={`filter-btn ${alertFilter === 'all' ? 'active' : ''}`} onClick={() => setAlertFilter('all')}>
                All ({complianceAlerts.length})
              </button>
              <button className={`filter-btn ${alertFilter === 'high' ? 'active' : ''}`} onClick={() => setAlertFilter('high')}>
                Critical ({complianceAlerts.filter((a) => a.severity === 'high').length})
              </button>
              <button className={`filter-btn ${alertFilter === 'medium' ? 'active' : ''}`} onClick={() => setAlertFilter('medium')}>
                Medium ({complianceAlerts.filter((a) => a.severity === 'medium').length})
              </button>
              <button className={`filter-btn ${alertFilter === 'low' ? 'active' : ''}`} onClick={() => setAlertFilter('low')}>
                Low ({complianceAlerts.filter((a) => a.severity === 'low').length})
              </button>
            </div>
          </div>

          <div className="alerts-list">
            {filtered.length === 0 ? (
              <p style={{ padding: '1rem', color: 'var(--text-muted, #888)' }}>No alerts in this category.</p>
            ) : (
              filtered.map((alert) => (
                <div key={alert.id} className={`alert-item ${alert.severity}`}>
                  <div className="alert-content">
                    <h4>{alert.message}</h4>
                    <div className="alert-meta">
                      <span className="alert-date">{alert.date ? new Date(alert.date).toLocaleDateString() : '—'}</span>
                      {alert.autoGenerated && <span className="auto-badge">Auto-detected</span>}
                    </div>
                  </div>
                  <div className="alert-controls">
                    <button className="btn-link">View Details</button>
                    <button className="btn-link">Resolve</button>
                    <button className="btn-link">Dismiss</button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        <div className="monitoring-features">
          <h3>Automated Monitoring</h3>
          <div className="features-grid">
            <div className="feature-card">
              <h4>Taxable Event Detection</h4>
              <p>Automatically detects stock sales, dividends, business income, and other taxable events</p>
              <div className="feature-status">
                <span className="status-badge active">Active</span>
                <span className="status-detail">247 events detected this month</span>
              </div>
            </div>
            <div className="feature-card">
              <h4>Deadline Tracking</h4>
              <p>Monitors filing deadlines across all jurisdictions with automatic reminders</p>
              <div className="feature-status">
                <span className="status-badge active">Active</span>
                <span className="status-detail">{complianceDeadlines.length} upcoming deadlines</span>
              </div>
            </div>
            <div className="feature-card">
              <h4>Risk Assessment</h4>
              <p>Continuous evaluation of compliance risk based on transactions and behavior</p>
              <div className="feature-status">
                <span className="status-badge low-risk">Low Risk</span>
                <span className="status-detail">94% compliance score</span>
              </div>
            </div>
            <div className="feature-card">
              <h4>Rule Updates</h4>
              <p>Automatically updates tax rules and thresholds when changes are detected</p>
              <div className="feature-status">
                <span className="status-badge active">Active</span>
                <span className="status-detail">Last update: Jan 10, 2025</span>
              </div>
            </div>
          </div>
        </div>

        <div className="compliance-timeline">
          <h3>Compliance Timeline</h3>
          <div className="timeline">
            <div className="timeline-item completed">
              <div className="timeline-content">
                <h4>Q4 2024 Tax Return Filed</h4>
                <p>US Federal Form 1120 submitted successfully</p>
                <span className="timeline-date">Jan 15, 2025</span>
              </div>
            </div>
            <div className="timeline-item upcoming">
              <div className="timeline-content">
                <h4>UK VAT Return Due</h4>
                <p>Q4 VAT return submission deadline</p>
                <span className="timeline-date">Feb 28, 2025</span>
              </div>
            </div>
            <div className="timeline-item upcoming">
              <div className="timeline-content">
                <h4>Annual Tax Planning Review</h4>
                <p>Comprehensive tax strategy review</p>
                <span className="timeline-date">Mar 15, 2025</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TaxMonitoring;
