# Generated by Django 4.2.7 on 2026-04-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_backfill_entity_linked_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='accepted', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default=None, max_length=20, null=True),
        ),
    ]
