---
all:
  vars:
    env: prod
    atc_registry_url: "{{ lookup('env', 'REGISTRY_URL') }}"

  children:
    bastion:
      hosts:
        atc-prod-bastion-01:
          ansible_host: REPLACE_WITH_FLOATING_IP
          ansible_user: ubuntu

    api:
      hosts:
        atc-prod-ledger-01:
          ansible_host: 10.40.1.10
          atc_service: ledger
        atc-prod-ledger-02:
          ansible_host: 10.40.1.11
          atc_service: ledger
        atc-prod-ledger-03:
          ansible_host: 10.40.1.12
          atc_service: ledger
        atc-prod-accounts-01:
          ansible_host: 10.40.1.13
          atc_service: accounts
        atc-prod-accounts-02:
          ansible_host: 10.40.1.14
          atc_service: accounts
        atc-prod-accounts-03:
          ansible_host: 10.40.1.15
          atc_service: accounts
        atc-prod-risk-01:
          ansible_host: 10.40.1.16
          atc_service: risk
        atc-prod-risk-02:
          ansible_host: 10.40.1.17
          atc_service: risk
        atc-prod-reporting-01:
          ansible_host: 10.40.1.18
          atc_service: reporting
        atc-prod-reporting-02:
          ansible_host: 10.40.1.19
          atc_service: reporting

    database:
      hosts:
        atc-prod-db-01:
          ansible_host: 10.40.1.20
          atc_service: db
        atc-prod-db-02:
          ansible_host: 10.40.1.21
          atc_service: db

  vars:
    ansible_ssh_common_args: >-
      -o ProxyJump=ubuntu@{{ hostvars['atc-prod-bastion-01']['ansible_host'] }}
      -o StrictHostKeyChecking=no
