---
all:
  vars:
    env: stage
    atc_registry_url: "{{ lookup('env', 'REGISTRY_URL') }}"

  children:
    bastion:
      hosts:
        lgx-stage-bastion-01:
          ansible_host: REPLACE_WITH_FLOATING_IP
          ansible_user: ubuntu

    api:
      hosts:
        lgx-stage-ledger-01:
          ansible_host: 10.30.1.10
          atc_service: ledger
        lgx-stage-ledger-02:
          ansible_host: 10.30.1.11
          atc_service: ledger
        lgx-stage-accounts-01:
          ansible_host: 10.30.1.12
          atc_service: accounts
        lgx-stage-accounts-02:
          ansible_host: 10.30.1.13
          atc_service: accounts
        lgx-stage-risk-01:
          ansible_host: 10.30.1.14
          atc_service: risk
        lgx-stage-reporting-01:
          ansible_host: 10.30.1.15
          atc_service: reporting

    database:
      hosts:
        lgx-stage-db-01:
          ansible_host: 10.30.1.20
          atc_service: db

  vars:
    ansible_ssh_common_args: >-
      -o ProxyJump=ubuntu@{{ hostvars['lgx-stage-bastion-01']['ansible_host'] }}
      -o StrictHostKeyChecking=no
