# Generated by Django 4.2.7 on 2026-04-08 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0016_rename_finances_ba_banking_d210e8_idx_finances_ba_banking_d54ffd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityShareClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('class_type', models.CharField(choices=[('common', 'Common'), ('preferred', 'Preferred'), ('esop', 'ESOP'), ('warrant', 'Warrant'), ('safe', 'SAFE'), ('convertible', 'Convertible')], default='common', max_length=20)),
                ('authorized_shares', models.BigIntegerField(default=0)),
                ('issued_shares', models.BigIntegerField(default=0)),
                ('liquidation_preference', models.CharField(blank=True, default='', max_length=255)),
                ('voting_rights', models.BooleanField(default=True)),
                ('par_value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_share_classes', to='finances.entity')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EquityShareholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('shareholder_type', models.CharField(choices=[('individual', 'Individual'), ('entity', 'Entity'), ('employee', 'Employee'), ('investor', 'Investor')], default='individual', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('beneficial_owner', models.BooleanField(default=False)),
                ('voting_rights_percent', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('kyc_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('aml_status', models.CharField(blank=True, default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equity_shareholders', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_shareholders', to='finances.entity')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('workspace', 'name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceEquityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_type', models.CharField(choices=[('standalone', 'Standalone'), ('accounting', 'Accounting'), ('equity', 'Equity'), ('combined', 'Combined')], default='accounting', max_length=20)),
                ('equity_enabled', models.BooleanField(default=False)),
                ('ownership_registry_enabled', models.BooleanField(default=False)),
                ('cap_table_enabled', models.BooleanField(default=False)),
                ('valuation_enabled', models.BooleanField(default=False)),
                ('equity_transactions_enabled', models.BooleanField(default=False)),
                ('governance_reporting_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equity_profile', to='finances.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EquityValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('dcf', 'DCF'), ('comps', 'Comparables'), ('market', 'Market'), ('board', 'Board Approved')], default='board', max_length=20)),
                ('valuation_date', models.DateField()),
                ('enterprise_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('equity_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('price_per_share', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('market_notes', models.TextField(blank=True, default='')),
                ('benchmark_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_valuations', to='finances.entity')),
            ],
            options={
                'ordering': ['-valuation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue'), ('transfer', 'Transfer'), ('exercise', 'Exercise'), ('cancellation', 'Cancellation'), ('conversion', 'Conversion')], max_length=20)),
                ('quantity', models.BigIntegerField(default=0)),
                ('price_per_share', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('effective_date', models.DateField()),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed')], default='draft', max_length=20)),
                ('compliance_checked', models.BooleanField(default=False)),
                ('digital_signature_required', models.BooleanField(default=True)),
                ('audit_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equity_transactions', to=settings.AUTH_USER_MODEL)),
                ('share_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='equity.equityshareclass')),
                ('shareholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='equity.equityshareholder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_transactions', to='finances.entity')),
            ],
            options={
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(max_length=100)),
                ('reporting_period', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='ready', max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_equity_reports', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_reports', to='finances.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityFundingRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('instrument_type', models.CharField(choices=[('equity', 'Equity'), ('safe', 'SAFE'), ('convertible_note', 'Convertible Note'), ('warrant', 'Warrant'), ('option', 'Option')], default='equity', max_length=30)),
                ('announced_at', models.DateField(blank=True, null=True)),
                ('pre_money_valuation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('price_per_share', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_funding_rounds', to='finances.entity')),
            ],
            options={
                'ordering': ['-announced_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(default=0)),
                ('diluted_quantity', models.BigIntegerField(default=0)),
                ('ownership_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('vesting_start', models.DateField(blank=True, null=True)),
                ('vesting_end', models.DateField(blank=True, null=True)),
                ('strike_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='equity.equityshareclass')),
                ('shareholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='equity.equityshareholder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_holdings', to='finances.entity')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('workspace', 'shareholder', 'share_class')},
            },
        ),
    ]
