# Generated by Django 4.2.7 on 2026-04-08 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_rename_finances_ba_banking_d210e8_idx_finances_ba_banking_d54ffd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equity', '0002_equityexerciserequest_equitygrant_equityvestingevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityDeliveryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('document', 'Document'), ('webhook', 'Webhook')], max_length=20)),
                ('event_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('document_payload', models.JSONField(blank=True, default=dict)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='equity.equitysharecertificate')),
                ('exercise_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='equity.equityexerciserequest')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='equity.equitygrant')),
                ('payroll_tax_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='equity.equitypayrolltaxevent')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_delivery_logs', to=settings.AUTH_USER_MODEL)),
                ('vesting_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_logs', to='equity.equityvestingevent')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_delivery_logs', to='finances.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityExternalAdapterConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adapter_type', models.CharField(choices=[('payroll', 'Payroll'), ('payment', 'Payment')], max_length=20)),
                ('provider_name', models.CharField(max_length=120)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('auth_scheme', models.CharField(default='Bearer', max_length=40)),
                ('endpoint_path', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('default_headers', models.JSONField(blank=True, default=dict)),
                ('adapter_settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equity_adapter_configs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_adapter_configs', to='finances.entity')),
            ],
            options={
                'ordering': ['adapter_type', 'provider_name'],
                'unique_together': {('workspace', 'adapter_type', 'provider_name')},
            },
        ),
    ]
