# Generated by Django 4.2.7 on 2026-04-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0003_equitydeliverylog_equityexternaladapterconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydeliverylog',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='equity/delivery_documents/'),
        ),
        migrations.AddField(
            model_name='equitygrant',
            name='grant_package_file',
            field=models.FileField(blank=True, null=True, upload_to='equity/grant_packages/'),
        ),
        migrations.AddField(
            model_name='equitysharecertificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='equity/certificates/'),
        ),
    ]
