# Generated by Django 4.2.7 on 2026-04-08 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equity', '0004_equitydeliverylog_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityfundinground',
            name='apply_pro_rata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equityfundinground',
            name='new_shares_issued',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equityfundinground',
            name='option_pool_top_up',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equityfundinground',
            name='post_money_valuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='equityfundinground',
            name='scenario_assumptions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='equityfundinground',
            name='share_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_rounds', to='equity.equityshareclass'),
        ),
        migrations.AddField(
            model_name='equityholding',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='equityholding',
            name='issue_price_per_share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='equityholding',
            name='pro_rata_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityholding',
            name='pro_rata_take_up_percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='anti_dilution_basis',
            field=models.CharField(choices=[('broad_based', 'Broad-Based'), ('narrow_based', 'Narrow-Based')], default='broad_based', max_length=30),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='anti_dilution_type',
            field=models.CharField(choices=[('none', 'None'), ('full_ratchet', 'Full Ratchet'), ('weighted_average', 'Weighted Average')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='conversion_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='liquidation_seniority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='participating_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='participation_cap_multiple',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='preference_multiple',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='equityshareclass',
            name='pro_rata_rights',
            field=models.BooleanField(default=False),
        ),
    ]
