# Generated by Django 4.2.7 on 2026-04-08 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0016_rename_finances_ba_banking_d210e8_idx_finances_ba_banking_d54ffd_idx_and_more'),
        ('equity', '0005_equityfundinground_apply_pro_rata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityScenarioApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('reporting_period', models.CharField(blank=True, default='', max_length=100)),
                ('scenario_payload', models.JSONField(blank=True, default=dict)),
                ('analysis_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('committed', 'Committed')], default='pending', max_length=20)),
                ('board_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('legal_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('board_decided_at', models.DateTimeField(blank=True, null=True)),
                ('legal_decided_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_approved_equity_scenarios', to=settings.AUTH_USER_MODEL)),
                ('committed_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_approval_records', to='equity.equityfundinground')),
                ('legal_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_approved_equity_scenarios', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_equity_scenario_approvals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_scenario_approvals', to='finances.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityOptionPoolReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_shares', models.BigIntegerField(default=0)),
                ('allocated_shares', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funding_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='option_pool_reserves', to='equity.equityfundinground')),
                ('share_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_pool_reserves', to='equity.equityshareclass')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_option_pool_reserves', to='finances.entity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
