# Generated by Django 4.2.7 on 2026-04-08 07:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_rename_finances_ba_banking_d210e8_idx_finances_ba_banking_d54ffd_idx_and_more'),
        ('equity', '0006_equityscenarioapproval_equityoptionpoolreserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='board_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='board_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='board_last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='legal_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='legal_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equityscenarioapproval',
            name='legal_last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EquityScenarioApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('board_sla_hours', models.PositiveIntegerField(default=72)),
                ('legal_sla_hours', models.PositiveIntegerField(default=72)),
                ('escalation_enabled', models.BooleanField(default=True)),
                ('escalation_grace_hours', models.PositiveIntegerField(default=24)),
                ('reminder_frequency_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_escalation_reviewers', models.ManyToManyField(blank=True, related_name='equity_board_escalation_policies', to='finances.entitystaff')),
                ('board_reviewers', models.ManyToManyField(blank=True, related_name='equity_board_review_policies', to='finances.entitystaff')),
                ('legal_escalation_reviewers', models.ManyToManyField(blank=True, related_name='equity_legal_escalation_policies', to='finances.entitystaff')),
                ('legal_reviewers', models.ManyToManyField(blank=True, related_name='equity_legal_review_policies', to='finances.entitystaff')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equity_scenario_approval_policy', to='finances.entity')),
            ],
        ),
    ]
