# Generated by Django 4.2.7 on 2026-04-08 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equity', '0007_equityscenarioapproval_board_due_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equityscenarioapprovalpolicy',
            name='require_designated_backups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equityscenarioapprovalpolicy',
            name='require_explicit_reviewers',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EquityScenarioApprovalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('submitted', 'Submitted'), ('board_approved', 'Board Approved'), ('legal_approved', 'Legal Approved'), ('rejected', 'Rejected'), ('reminder', 'Reminder Sent'), ('escalated', 'Escalated'), ('committed', 'Committed')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equity_scenario_approval_events', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='equity.equityscenarioapproval')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
