import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';

import { useEnterprise } from '../../context/EnterpriseContext';
import './EnterpriseActionPages.css';
import './EnterpriseTaxCompliance.css';

const EnterpriseTaxCompliance = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const navigate = useNavigate();
  const activeSection = searchParams.get('section') || 'overview';

  const {
    entities,
    fetchEntityTaxProfiles,
    createTaxProfile,
    fetchEntityComplianceDocuments,
    fetchEntityComplianceDeadlines,
    fetchEntityTaxCalculations,
  } = useEnterprise();

  const [selectedEntityId, setSelectedEntityId] = useState('');
  const selectedEntity = useMemo(() => {
    if (!selectedEntityId) return null;
    return entities.find((e) =>String(e.id) === String(selectedEntityId)) || null;
  }, [entities, selectedEntityId]);

  const [taxProfiles, setTaxProfiles] = useState([]);
  const [documents, setDocuments] = useState([]);
  const [complianceDeadlines, setComplianceDeadlines] = useState([]);
  const [taxCalculations, setTaxCalculations] = useState([]);
  const [dataError, setDataError] = useState(null);

  const [showCountrySelector, setShowCountrySelector] = useState(false);

  useEffect(() => {
    if (selectedEntityId) return;
    if (!entities || entities.length === 0) return;
    setSelectedEntityId(String(entities[0].id));
  }, [entities, selectedEntityId]);

  useEffect(() => {
    const load = async () => {
      if (!selectedEntityId) return;
      setDataError(null);
      try {
        const [profiles, docs, deadlines, calcs] = await Promise.all([
          fetchEntityTaxProfiles(selectedEntityId),
          fetchEntityComplianceDocuments(selectedEntityId),
          fetchEntityComplianceDeadlines(selectedEntityId),
          fetchEntityTaxCalculations(selectedEntityId),
        ]);

        const uiProfiles = (profiles || []).map((p) => ({
          id: p.id,
          country: p.country,
          status: p.status,
          lastUpdated: p.updated_at || p.created_at,
          entities: 1,
          taxRules: {
            ...(p.tax_rules || {}),
            lastRuleUpdate: p.last_rule_update || null,
            autoUpdate: p.auto_update !== false,
          },
          residencyStatus: p.residency_status || 'detected',
          complianceScore: Number.isFinite(p.compliance_score) ? p.compliance_score : 0,
        }));

        const uiDocuments = (docs || []).map((d) => {
          const typeMap = {
            license: 'form',
            registration: 'form',
            tax_certificate: 'form',
            insurance: 'report',
            permit: 'form',
            contract: 'audit',
            certificate: 'form',
            other: 'report',
          };
          const statusMap = {
            active: 'ready',
            renewed: 'ready',
            expiring_soon: 'ready',
            expired: 'failed',
          };

          return {
            id: d.id,
            name: d.title,
            type: typeMap[d.document_type] || 'report',
            status: statusMap[d.status] || 'ready',
            size: d.file_path ? '—' : '-',
            date: d.created_at || d.issue_date,
            autoGenerated: false,
            raw: d,
          };
        });

        setTaxProfiles(uiProfiles);
        setDocuments(uiDocuments);
        setComplianceDeadlines(deadlines || []);
        setTaxCalculations(calcs || []);
      } catch (err) {
        console.error(err);
        setDataError(err?.message || 'Failed to load Tax & Compliance data');
        setTaxProfiles([]);
        setDocuments([]);
        setComplianceDeadlines([]);
        setTaxCalculations([]);
      }
    };

    load();
  }, [
    selectedEntityId,
    fetchEntityTaxProfiles,
    fetchEntityComplianceDocuments,
    fetchEntityComplianceDeadlines,
    fetchEntityTaxCalculations,
  ]);

  const complianceAlerts = useMemo(() => {
    const now = new Date();
    return (complianceDeadlines || []).map((d) => {
      const deadlineDate = d.deadline_date ? new Date(d.deadline_date) : null;
      const daysLeft = deadlineDate ? Math.ceil((deadlineDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)) : null;

      let severity = 'low';
      if (d.status === 'overdue') severity = 'high';
      else if (daysLeft !== null && daysLeft <= 7) severity = 'high';
      else if (daysLeft !== null && daysLeft <= 30) severity = 'medium';

      return {
        id: d.id,
        type: 'deadline',
        message: d.title,
        severity,
        date: d.deadline_date,
        autoGenerated: false,
        actions: ['view', 'set-reminder'],
        raw: d,
      };
    });
  }, [complianceDeadlines]);

  const calculations = useMemo(() => {
    const empty = {
      incomeTax: { amount: 0, breakdown: { salary: 0, business: 0 }, lastCalculated: null },
      capitalGains: { amount: 0, breakdown: { stocks: 0, crypto: 0 }, lastCalculated: null },
      dividends: { amount: 0, breakdown: { qualified: 0, ordinary: 0 }, lastCalculated: null },
      withholding: { amount: 0, breakdown: { federal: 0, state: 0 }, lastCalculated: null },
      vat: { amount: 0, breakdown: { sales: 0, imports: 0 }, lastCalculated: null },
      quarterlyProjection: { amount: 0, confidence: 0, lastProjected: null },
    };

    if (!Array.isArray(taxCalculations) || taxCalculations.length === 0) return empty;

    const sorted = [...taxCalculations].sort((a, b) => {
      const ad = new Date(a.created_at || 0).getTime();
      const bd = new Date(b.created_at || 0).getTime();
      return bd - ad;
    });

    const latestCorporate = sorted.find((c) => c.calculation_type === 'corporate') || null;
    const latestVat = sorted.find((c) => c.calculation_type === 'vat') || null;

    return {
      ...empty,
      incomeTax: latestCorporate
        ? {
            amount: Number(latestCorporate.calculated_tax || 0),
            breakdown: { salary: 0, business: Number(latestCorporate.taxable_income || 0) },
            lastCalculated: latestCorporate.created_at || null,
          }
        : empty.incomeTax,
      vat: latestVat
        ? {
            amount: Number(latestVat.calculated_tax || 0),
            breakdown: { sales: Number(latestVat.taxable_income || 0), imports: 0 },
            lastCalculated: latestVat.created_at || null,
          }
        : empty.vat,
    };
  }, [taxCalculations]);

  const overallComplianceScore = useMemo(() => {
    if (!Array.isArray(taxProfiles) || taxProfiles.length === 0) return 0;
    const avg = taxProfiles.reduce((sum, p) => sum + (Number.isFinite(p.complianceScore) ? p.complianceScore : 0), 0) / taxProfiles.length;
    return Math.max(0, Math.min(100, Math.round(avg)));
  }, [taxProfiles]);

  const overallComplianceLabel = useMemo(() => {
    if (overallComplianceScore >= 90) return { label: 'Excellent', className: 'excellent' };
    if (overallComplianceScore >= 75) return { label: 'Good', className: 'good' };
    if (overallComplianceScore >= 50) return { label: 'Fair', className: 'fair' };
    return { label: 'Needs Attention', className: 'warning' };
  }, [overallComplianceScore]);

  const recentActivityItems = useMemo(() => {
    const items = [];
    const latestProfile = Array.isArray(taxProfiles) && taxProfiles.length
      ? [...taxProfiles].sort((a, b) => new Date(b.lastUpdated || 0) - new Date(a.lastUpdated || 0))[0]
      : null;
    if (latestProfile?.lastUpdated) {
      items.push({
        key: `profile-${latestProfile.id}`,
        kind: 'info',
        message: `Tax profile updated for ${latestProfile.country}`,
        when: latestProfile.lastUpdated,
        action: 'View',
      });
    }

    const latestCalc = Array.isArray(taxCalculations) && taxCalculations.length
      ? [...taxCalculations].sort((a, b) => new Date(b.created_at || 0) - new Date(a.created_at || 0))[0]
      : null;
    if (latestCalc?.created_at) {
      items.push({
        key: `calc-${latestCalc.id}`,
        kind: 'success',
        message: `Tax calculation saved (${latestCalc.calculation_type} - ${latestCalc.jurisdiction})`,
        when: latestCalc.created_at,
        action: 'View',
      });
    }

    const latestDoc = Array.isArray(documents) && documents.length
      ? [...documents].sort((a, b) => new Date(b.date || 0) - new Date(a.date || 0))[0]
      : null;
    if (latestDoc?.date) {
      items.push({
        key: `doc-${latestDoc.id}`,
        kind: 'success',
        message: `Compliance document updated (${latestDoc.name})`,
        when: latestDoc.date,
        action: 'View',
      });
    }

    return items.slice(0, 4);
  }, [taxProfiles, taxCalculations, documents]);

  const upcomingDeadlines = useMemo(() => {
    const list = Array.isArray(complianceDeadlines) ? [...complianceDeadlines] : [];
    list.sort((a, b) => new Date(a.deadline_date || 0) - new Date(b.deadline_date || 0));
    return list.slice(0, 5);
  }, [complianceDeadlines]);

  // Available countries for tax profiles
  const availableCountries = [
    { code: 'US', name: 'United States', flag: '', taxTypes: ['federal', 'state'], autoDetectable: true },
    { code: 'UK', name: 'United Kingdom', flag: '', taxTypes: ['corporation'], autoDetectable: true },
    { code: 'CA', name: 'Canada', flag: '', taxTypes: ['federal', 'provincial'], autoDetectable: true },
    { code: 'DE', name: 'Germany', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'FR', name: 'France', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'AU', name: 'Australia', flag: '', taxTypes: ['corporate'], autoDetectable: true },
    { code: 'ZA', name: 'South Africa', flag: '', taxTypes: ['corporate'], autoDetectable: false },
    { code: 'SG', name: 'Singapore', flag: '', taxTypes: ['corporate'], autoDetectable: false },
  ];

  const handleCountrySelect = async (countryCode) => {
    setShowCountrySelector(false);

    if (!selectedEntityId) return;

    const selected = availableCountries.find((c) => c.code === countryCode);
    const countryName = selected?.name || countryCode;

    try {
      await createTaxProfile({
        entity: selectedEntityId,
        country: countryName,
        status: 'active',
        tax_rules: {},
        auto_update: true,
        residency_status: 'detected',
      });
      const refreshed = await fetchEntityTaxProfiles(selectedEntityId);
      const uiProfiles = (refreshed || []).map((p) => ({
        id: p.id,
        country: p.country,
        status: p.status,
        lastUpdated: p.updated_at || p.created_at,
        entities: 1,
        taxRules: {
          ...(p.tax_rules || {}),
          lastRuleUpdate: p.last_rule_update || null,
          autoUpdate: p.auto_update !== false,
        },
        residencyStatus: p.residency_status || 'detected',
        complianceScore: Number.isFinite(p.compliance_score) ? p.compliance_score : 0,
      }));
      setTaxProfiles(uiProfiles);
    } catch (err) {
      console.error(err);
      setDataError(err?.message || 'Failed to add tax profile');
    }
  };

  const renderOverview = () => (
    <div className="compliance-overview">
      {/* Quick Stats */}
      <div className="overview-stats">
        <div className="stat-card">
          <div className="stat-icon"></div>
          <div className="stat-content">
            <h3>{taxProfiles.filter(p => p.status === 'active').length}</h3>
            <p>Active Countries</p>
            <span className="stat-trend neutral">Based on entity profiles</span>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon"></div>
          <div className="stat-content">
            <h3>${calculations.quarterlyProjection.amount.toLocaleString()}</h3>
            <p>Quarterly Tax Projection</p>
            <span className="stat-trend neutral">No projection model yet</span>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon"></div>
          <div className="stat-content">
            <h3>{complianceAlerts.filter(a => a.severity === 'high').length}</h3>
            <p>Critical Alerts</p>
            <span className="stat-trend neutral">Derived from deadlines</span>
          </div>
        </div>
        <div className="stat-card">
          <div className="stat-icon"></div>
          <div className="stat-content">
            <h3>{documents.filter(d => d.status === 'ready').length}</h3>
            <p>Ready Documents</p>
            <span className="stat-trend neutral">From compliance vault</span>
          </div>
        </div>
      </div>

      {/* Quick Actions Bar */}
      <div className="quick-actions">
        <button className="quick-action-btn" onClick={() => navigate('/app/compliance/tax-calculator')}>
          Run Tax Calculation
        </button>
        <button className="quick-action-btn secondary" onClick={() => navigate('/app/compliance/monitoring')}>
          Check Compliance
        </button>
        <button className="quick-action-btn secondary" onClick={() => navigate('/app/compliance/filing')}>
          Filing Assistant
        </button>
        <button className="quick-action-btn secondary" onClick={() => navigate('/app/automation/ai-advisor')}>
          Ask AI Advisor
        </button>
      </div>

      {/* Compliance Health Dashboard */}
      <div className="compliance-health">
        <div className="health-header">
          <h3>Compliance Health Score</h3>
          <div className="health-score">
            <div className="score-circle">
              <span className="score-number">{overallComplianceScore}</span>
              <span className="score-label">/100</span>
            </div>
            <div className="score-details">
              <span className={`score-status ${overallComplianceLabel.className}`}>{overallComplianceLabel.label}</span>
              <span className="score-change">Calculated from profiles</span>
            </div>
          </div>
        </div>

        <div className="health-metrics">
          <div className="metric-item">
            <div className="metric-label">Tax Profiles</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${taxProfiles.length ? Math.min(100, overallComplianceScore) : 0}%`}}></div>
            </div>
            <span className="metric-value">{overallComplianceScore}%</span>
          </div>
          <div className="metric-item">
            <div className="metric-label">Documents</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${documents.length ? 100 : 0}%`}}></div>
            </div>
            <span className="metric-value">{documents.length}</span>
          </div>
          <div className="metric-item">
            <div className="metric-label">Upcoming Deadlines</div>
            <div className="metric-bar">
              <div className="metric-fill" style={{width: `${upcomingDeadlines.length ? 100 : 0}%`}}></div>
            </div>
            <span className="metric-value">{upcomingDeadlines.length}</span>
          </div>
        </div>
      </div>

      {/* Recent Activity */}
      <div className="recent-activity">
        <h3>Recent Activity</h3>
        <div className="activity-list">
          {recentActivityItems.length === 0 ? (
            <div className="activity-item">
              <div className="activity-icon info"></div>
              <div className="activity-content">
                <p>No activity yet for this entity</p>
                <span>Create a tax profile, upload a document, or run a calculation</span>
              </div>
            </div>
          ) : (
            recentActivityItems.map((item) => (
              <div key={item.key} className="activity-item">
                <div className={`activity-icon ${item.kind}`}> </div>
                <div className="activity-content">
                  <p>{item.message}</p>
                  <span>{item.when ? new Date(item.when).toLocaleString() : ''}</span>
                </div>
                <button className="btn-link">{item.action}</button>
              </div>
            ))
          )}
        </div>
      </div>

      {/* Upcoming Deadlines */}
      <div className="upcoming-deadlines">
        <h3>Upcoming Deadlines</h3>
        <div className="deadlines-list">
          {upcomingDeadlines.length === 0 ? (
            <div className="deadline-item normal">
              <div className="deadline-info">
                <h4>No deadlines yet</h4>
                <p>Create compliance deadlines for the selected entity</p>
              </div>
              <div className="deadline-status">
                <span className="status-badge normal">Empty</span>
              </div>
            </div>
          ) : (
            upcomingDeadlines.map((d) => (
              <div key={d.id} className={`deadline-item ${d.status === 'overdue' || d.status === 'due_soon' ? 'urgent' : 'normal'}`}>
                <div className="deadline-info">
                  <h4>{d.title}</h4>
                  <p>{d.deadline_type}</p>
                  <span className="deadline-date">Due: {d.deadline_date ? new Date(d.deadline_date).toLocaleDateString() : '—'}</span>
                </div>
                <div className="deadline-status">
                  <span className={`status-badge ${d.status === 'overdue' || d.status === 'due_soon' ? 'urgent' : 'normal'}`}>{d.status}</span>
                </div>
                <div className="deadline-actions">
                  <button className="btn-secondary">View</button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );

  const renderTaxProfiles = () => (
    <div className="tax-profiles-section">
      <div className="section-header">
        <h2>Multi-Country Tax Profiles</h2>
        <p>Auto-configured tax rules for global operations</p>
        <div className="header-actions">
          <button
            className="btn-secondary"
            onClick={() => setShowCountrySelector(true)}
          >
            Add Country
          </button>
          <button className="btn-link">
            Update All Rules
          </button>
        </div>
      </div>

      {/* Country Selector Modal */}
      {showCountrySelector && (
        <div className="modal-overlay" onClick={() => setShowCountrySelector(false)}>
          <div className="modal-content country-selector" onClick={e => e.stopPropagation()}>
            <div className="modal-header">
              <h3>Select Country for Tax Profile</h3>
              <button className="close-btn" onClick={() => setShowCountrySelector(false)}>

              </button>
            </div>
            <div className="country-grid">
              {availableCountries.map(country => (
                <div
                  key={country.code}
                  className="country-option"
                  onClick={() => handleCountrySelect(country.code)}
                >
                  <div className="country-flag">{country.flag}</div>
                  <div className="country-info">
                    <h4>{country.name}</h4>
                    <div className="country-details">
                      <span className="tax-types">
                        {country.taxTypes.join(', ')}
                      </span>
                      {country.autoDetectable && (
                        <span className="auto-detect-badge">Auto-detectable</span>
                      )}
                    </div>
                  </div>

                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      <div className="profiles-grid">
        {taxProfiles.map(profile => (
          <div key={profile.id} className="profile-card">
            <div className="profile-header">
              <div className="country-flag">
                {availableCountries.find(c => c.code === profile.country)?.flag || profile.country}
              </div>
              <div className={`status-badge ${profile.status}`}>
                {profile.status}
              </div>
              <div className="compliance-score">

                <span>{profile.complianceScore}%</span>
              </div>
            </div>
            <div className="profile-content">
              <h3>{availableCountries.find(c => c.code === profile.country)?.name || profile.country} Tax Profile</h3>

              <div className="profile-stats">
                <div className="stat">
                  <span className="label">Entities:</span>
                  <span className="value">{profile.entities}</span>
                </div>
                <div className="stat">
                  <span className="label">Last Updated:</span>
                  <span className="value">{new Date(profile.lastUpdated).toLocaleDateString()}</span>
                </div>
                <div className="stat">
                  <span className="label">Residency:</span>
                  <span className={`value ${profile.residencyStatus}`}>
                    {profile.residencyStatus}
                  </span>
                </div>
              </div>

              {/* Tax Rules Preview */}
              <div className="tax-rules-preview">
                <h4>Current Tax Rules</h4>
                <div className="rules-list">
                  {profile.country === 'US' && (
                    <>
                      <div className="rule-item">
                        <span>Federal Rate:</span>
                        <span>{profile.taxRules.federalRate}%</span>
                      </div>
                      <div className="rule-item">
                        <span>State Rates:</span>
                        <span>CA: {profile.taxRules.stateRates.CA}%, NY: {profile.taxRules.stateRates.NY}%</span>
                      </div>
                    </>
                  )}
                  {profile.country === 'UK' && (
                    <div className="rule-item">
                      <span>Corporation Tax:</span>
                      <span>{profile.taxRules.corporationTax}%</span>
                    </div>
                  )}
                  {profile.country === 'CA' && (
                    <>
                      <div className="rule-item">
                        <span>Federal Rate:</span>
                        <span>{profile.taxRules.federalRate}%</span>
                      </div>
                      <div className="rule-item">
                        <span>Provincial Rates:</span>
                        <span>ON: {profile.taxRules.provincialRates.ON}%, BC: {profile.taxRules.provincialRates.BC}%</span>
                      </div>
                    </>
                  )}
                </div>
                <div className="rule-update-info">

                  <span>Last rule update: {new Date(profile.taxRules.lastRuleUpdate).toLocaleDateString()}</span>
                  {profile.taxRules.autoUpdate && (
                    <span className="auto-update-badge">Auto-updating</span>
                  )}
                </div>
              </div>
            </div>
            <div className="profile-actions">
              <button className="btn-secondary">Configure</button>
              <button className="btn-link">View Rules</button>
              <button className="btn-link">Edit Profile</button>
            </div>
          </div>
        ))}
      </div>

      <div className="auto-update-notice">

        <div className="notice-content">
          <h4>Automatic Updates Active</h4>
          <p>Tax rules are automatically updated when changes are detected in supported jurisdictions. Last global update: January 10, 2025</p>
          <div className="update-stats">
            <span>247 jurisdictions monitored</span>
            <span>12 rule changes this month</span>
            <span>99.9% uptime</span>
          </div>
        </div>
      </div>

      {/* Residency Detection Section */}
      <div className="residency-detection">
        <h3>Residency Status Detection</h3>
        <p>Automatically detect and confirm tax residency status across jurisdictions</p>
        <div className="detection-controls">
          <button className="btn-primary">
            Run Detection Scan
          </button>
          <button className="btn-secondary">
            Review Detected Status
          </button>
        </div>
        <div className="detection-results">
          <div className="result-item">

            <span>US Residency: Confirmed (based on entity registrations)</span>
          </div>
          <div className="result-item">

            <span>UK Residency: Confirmed (based on permanent establishment)</span>
          </div>
          <div className="result-item">

            <span>CA Residency: Pending verification (awaiting additional documentation)</span>
          </div>
        </div>
      </div>
    </div>
  );

  const renderContent = () => {
    switch (activeSection) {
      case 'overview': return renderOverview();
      case 'profiles': return renderTaxProfiles();
      default: return renderOverview();
    }
  };

  return (
    <div className="enterprise-tax-compliance enterprise-action-page">
      <section className="action-page-hero">
        <div className="action-page-copy">
          <span className="action-page-kicker">Workspace — Tax & Compliance</span>
          <h1 className="action-page-title">Tax & Compliance</h1>
          <p className="action-page-subtitle">Monitor deadlines, filings, tax calculations, and jurisdiction risk from one operational control surface.</p>
          <div className="action-page-actions">
            <select
              className="entity-selector"
              value={selectedEntityId}
              onChange={(e) => setSelectedEntityId(e.target.value)}
              disabled={!entities || entities.length === 0}
            >
              {(!entities || entities.length === 0) ? (
                <option value="">No entities</option>
              ) : (
                entities.map((ent) => (
                  <option key={ent.id} value={String(ent.id)}>
                    {ent.name} ({ent.country})
                  </option>
                ))
              )}
            </select>
            {dataError ? <span className="status-badge warning">{dataError}</span> : null}
          </div>
        </div>
        <div className="action-page-badge">{selectedEntity?.country || 'Global'}</div>
      </section>

      <section className="action-page-stats">
        <div className="action-page-stat">
          <span className="action-page-stat-label">Compliance Score</span>
          <span className="action-page-stat-value">{overallComplianceScore}%</span>
          <span className="action-page-stat-caption">Current organization-wide compliance posture</span>
        </div>
        <div className="action-page-stat">
          <span className="action-page-stat-label">Active Alerts</span>
          <span className="action-page-stat-value">{complianceAlerts.length}</span>
          <span className="action-page-stat-caption">Critical and upcoming obligations requiring attention</span>
        </div>
        <div className="action-page-stat">
          <span className="action-page-stat-label">Documents</span>
          <span className="action-page-stat-value">{documents.length}</span>
          <span className="action-page-stat-caption">Compliance artifacts currently attached to the selected entity</span>
        </div>
      </section>

      {/* Section Navigation Header */}
      <div className="section-navigation">
        <button
          className={`nav-btn ${activeSection === 'overview' ? 'active' : ''}`}
          onClick={() => setSearchParams({ section: 'overview' })}
        >
          Overview
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/compliance/tax-center')}
        >
          Tax Profiles
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/compliance/tax-calculator')}
        >
          Tax Calculator
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/documents/vault')}
        >
          Documents
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/compliance/monitoring')}
        >
          Monitoring
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/documents/vault')}
        >
          Compliance Vault
        </button>
        <button
          className="nav-btn"
          onClick={() => navigate('/app/compliance/filing')}
        >
          Filing Assistant
        </button>
      </div>

      {/* Main Content */}
      <div className="compliance-main">
        {/* Content Area */}
        <div className="compliance-content">
          {renderContent()}
        </div>
      </div>
    </div>
  );
};

export default EnterpriseTaxCompliance;
