apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ledgrionyx-prod

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-backend.yaml
  - patch-app.yaml
  - patch-ingress.yaml

images:
  - name: ledgrionyx/backend
    newName: registry.example.com/ledgrionyx/backend
    newTag: prod
  - name: ledgrionyx/app
    newName: registry.example.com/ledgrionyx/app
    newTag: prod