apiVersion: v1
kind: ConfigMap
metadata:
  name: ledgrionyx-config
data:
  DJANGO_ALLOWED_HOSTS: "api.ledgrionyx.com"
  CORS_ALLOWED_ORIGINS: "https://app.ledgrionyx.com"
  CSRF_TRUSTED_ORIGINS: "https://app.ledgrionyx.com"
  DEPLOYMENT_ENVIRONMENT: "prod"
  APP_VERSION: "prod"