apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atc-capital-dev

resources:
  - ../../base
  - namespace.yaml

patchesStrategicMerge:
  - patch-config.yaml
  - patch-backend.yaml
  - patch-app.yaml
  - patch-ingress.yaml

images:
  - name: atc-capital/backend
    newName: registry.example.com/atc-capital/backend
    newTag: dev
  - name: atc-capital/app
    newName: registry.example.com/atc-capital/app
    newTag: dev